FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Authorization code based on user credentials

This POST request returns authorization code. It is based on filled email and password in request body. Use only in POSTMAN.

## setTokens - user [/questions]

### Ask for authorization tokens [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "email": "{{user-email}}",
            "password": "Connectedcar1"
        }

+ Response 200 (application/json)

    + Headers
    
            Authorization: Basic c2tvZGE6Q29ubmVjdGVkY2FyMQ==
            Location: /questions/2

    + Body

            {
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }